spring:
  application:
    name: libraryapi
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:15432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
#      ddl-auto: update
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-ss HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n
  file:
    name: library-api.log
  level:
    root: warn
    com:
      sipriano: trace
    org:
      springframework:
        web: debug
        security: trace

# trace -> rastreamento minucioso
# debug -> detalha fluxo e variáveis em execução
# info -> informações gerais do funcionamento da app
# warn -> avisos de eventos potencialmente problemáticos
# error -> erros q de algo especifico mas q n causam interrupção total

# os de cima tbm habilitam os de baixo, ordem de prioridade(error é só error)
springdoc:
  override-with-generic-response: false